name: Keep Render App Alive

on:
  schedule:
    # Run the action every 10 minutes
    - cron: '*/5 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -I https://gfg-vu.onrender.com
