name: Keep Render App Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          # Send the ping and close connection after 5 seconds
          curl --silent --max-time 5 https://gfg-vu.onrender.com
