name: Keep Render App Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/1 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -I https://gfg-vu.onrender.com
